import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import React from "react";
import {Navbar} from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function GeneralLayout({children}: Readonly<{ children: React.ReactNode; }>) {
  return (<>
      <Navbar></Navbar>
      <main className="flex flex-col items-center p-24">
        {children}
      </main>
    </>
  );
}
